name       : kf6-kglobalaccel
version    : 5.248.0
release    : 3
source     :
    - https://download.kde.org/unstable/frameworks/5.248.0/kglobalaccel-5.248.0.tar.xz : 4c98cc8a2f1f0f6bd487465d04a80b4b10e45693954a6dc078da5904cf7449bc
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Global desktop keyboard shortcuts
description: |
    KGlobalAccel allows you to have global accelerators that are independent of the focused window. Unlike regular shortcuts, the application's window does not need focus for them to be activated.
builddeps  :
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
