name       : plasma-systemmonitor
version    : 5.92.0
release    : 30
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-systemmonitor-5.92.0.tar.xz : 2a38ed3e2497cdd1d2832c8fe09a4663a2b85ec48beb2024be55562882f7af4c
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kirigami-addons-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kf6-kirigami
    - qt6-quickcontrols2
    - kf6-ksystemstats
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
