name       : drkonqi
version    : 5.92.0
release    : 89
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/drkonqi-5.92.0.tar.xz : 116f7b9e7d6a08025f8d56f2ad9e1b6d5ac3126ef720ae4891508d696751d524
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Quick)
    - kf6-kcrash-devel
    - kf6-kdeclarative-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kuserfeedback-devel
    - kf6-kwallet-devel
    - kf6-syntax-highlighting-devel
    - polkit-qt-1-qt6-devel
rundep     :
    - gdb
setup      : |
    %cmake_kf6 -DWITH_PYTHON_VENDORING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
