name       : kf6-kio
version    : 5.248.0
release    : 4
source     :
    - https://download.kde.org/unstable/frameworks/5.248.0/kio-5.248.0.tar.xz : eecfc5d9f829847c3b955046955a2d3bcd8740e746fc6feeb4f0873ee57dc58e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kbookmarks-devel
    - kf6-kcolorscheme-devel
    - kf6-kcompletion-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kded-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-kiconthemes-devel
    - kf6-kitemviews-devel
    - kf6-kjobwidgets-devel
    - kf6-kservice-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kwindowsystem-devel
    - kf6-solid-devel
    # TODO package switcheroo-control
rundeps    :
    - kf6-kded
    - devel :
        - kf6-kbookmarks-devel
        - kf6-kcompletion-devel
        - kf6-kconfigwidgets-devel
        - kf6-kcrash-devel
        - kf6-kdbusaddons-devel
        - kf6-kguiaddons-devel
        - kf6-kiconthemes-devel
        - kf6-kitemviews-devel
        - kf6-kjobwidgets-devel
        - kf6-kservice-devel
        - kf6-kwidgetsaddons-devel
        - kf6-kwindowsystem-devel
        - kf6-solid-devel
        - qt6-base-devel
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc/HTML
patterns   :
    - main :
        - /usr/lib64/libkuriikwsfiltereng_private.so
