name       : kf6-kirigami-addons
version    : 0.11.90
release    : 4
source     :
    - https://download.kde.org/unstable/kirigami-addons/kirigami-addons-0.11.90.tar.xz : 7bf925099924aa7b6fa123c64cdf1085bcc3fcc80f7050b9425cec7fe461bcae
license    : GPL-2.0-or-later
component  : programming.library
summary    : Convergent visual components ("widgets") for Kirigami-based applications
description: |
    A set of "widgets" i.e visual end user components along with a code to support them. Components are usable by both touch and desktop experiences providing a native experience on both, and look native with any QQC2 style (qqc2-desktop-theme, Material or Plasma)
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6QuickControls2)
    - extra-cmake-modules
    - kf6-ki18n-devel
    - kf6-kirigami-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
